version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./services/api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build: ./services/worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
